"""hash needs more chars

Revision ID: 5c5cac4082c8
Revises: 5f6c70e5a3a4
Create Date: 2022-07-14 20:32:38.278538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c5cac4082c8'
down_revision = '5f6c70e5a3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    op.alter_column('hashed_password', sa.VARCHAR(length=1000))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
