"""change file_url to file_name

Revision ID: 5f6c70e5a3a4
Revises: ea274d2b14de
Create Date: 2022-07-12 18:47:07.308130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6c70e5a3a4'
down_revision = 'ea274d2b14de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('file_name', sa.String(length=1000), nullable=True))
    op.drop_column('tasks', 'file_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('file_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'file_name')
    # ### end Alembic commands ###
