"""Second migration with status change

Revision ID: 7523624d4947
Revises: 57184da021d2
Create Date: 2022-05-31 18:43:25.263847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7523624d4947'
down_revision = '57184da021d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=True))
    op.drop_column('tasks', 'done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
