"""remove camel case

Revision ID: c51adbc57ae9
Revises: 551fd13cd150
Create Date: 2022-06-18 21:25:32.857267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c51adbc57ae9'
down_revision = '551fd13cd150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasklists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('tasklists_userId_fkey', 'tasklists', type_='foreignkey')
    op.create_foreign_key(None, 'tasklists', 'users', ['user_id'], ['id'])
    op.drop_column('tasklists', 'userId')
    op.add_column('tasks', sa.Column('task_list_id', sa.Integer(), nullable=False))
    op.drop_constraint('tasks_taskListId_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'tasklists', ['task_list_id'], ['id'])
    op.drop_column('tasks', 'taskListId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('taskListId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_taskListId_fkey', 'tasks', 'tasklists', ['taskListId'], ['id'])
    op.drop_column('tasks', 'task_list_id')
    op.add_column('tasklists', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tasklists', type_='foreignkey')
    op.create_foreign_key('tasklists_userId_fkey', 'tasklists', 'users', ['userId'], ['id'])
    op.drop_column('tasklists', 'user_id')
    # ### end Alembic commands ###
